Repository ho991217/danfesta2024, pull requests merged in 2024-05, with the labels that each got.

#39 feaat[stoybook] : 스토리북 적용
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  .vscode/settings.json
  README.md
  components/common/floating-ticket.tsx
  next.config.mjs
  package.json
  stories/common/Button.stories.tsx
  stories/common/Carousel.stories.tsx
  stories/common/Footer.stories.tsx
  stories/common/Form.stories.tsx
  stories/common/Overlay.stories.tsx
  stories/common/ad-banner.stories.tsx
  stories/common/bottom-sheet.stories.tsx
  stories/common/floating-ticket.stories.tsx
  stories/common/locale-switcher.stories.tsx
  stories/components/admin/Keypad.stories.tsx
  stories/components/admin/qr-reader.stories.tsx
  stories/components/admin/result-tile.stories.tsx
  stories/components/my_ticket/qr-code.stories.tsx
  stories/components/ticketing/Form.stories.tsx
  stories/components/ticketing/refetch-button.stories.tsx
  stories/ui/Accordion.stories.tsx
  stories/ui/Avatar.stories.tsx
  stories/ui/Card.stories.tsx
  stories/ui/Checkbox.stories.tsx
  stories/ui/Dropdown-Menu.stories.tsx
  stories/ui/Select.stories.tsx
  stories/ui/Separator.stories.tsx
  stories/ui/Sheet.stories.tsx
  stories/ui/Table.stories.tsx
  yarn.lock
Labels: documentation

#58 chore: 공지 내용 수정
  app/[locale]/(back-nav)/(padded)/notice/page.tsx
Labels: documentation

#60 feat: 개인정보동의항목 컴포넌트화
  app/[locale]/(back-nav)/(padded)/verify/page.tsx
  app/[locale]/(back-nav)/(padded)/verify/terms.tsx
  app/components/common/animated/animated-check.tsx
  app/components/common/animated/types.ts
  app/components/common/bottom-sheet/index.tsx
  app/components/common/button/index.tsx
  app/components/common/form/index.tsx
  app/components/common/form/terms.tsx
  app/components/ui/checkbox.tsx
  app/hooks/use-bottom-sheet.ts
Labels: enhancement

#62 푸터 수정
  app/[locale]/(back-nav)/(padded)/my-tickets/page.tsx
  app/[locale]/(back-nav)/(padded)/mypage/page.tsx
  app/[locale]/(back-nav)/(padded)/notice/page.tsx
  app/[locale]/(back-nav)/(padded)/password/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  app/[locale]/(back-nav)/(padded)/verify/page.tsx
  app/[locale]/(back-nav)/(padded)/verify/terms.tsx
  app/[locale]/(back-nav)/lineup/page.tsx
  app/components/common/animated/animated-check.tsx
  app/components/common/animated/types.ts
  app/components/common/back-button.tsx
  app/components/common/bottom-sheet/index.tsx
  app/components/common/button/index.tsx
  app/components/common/footer.tsx
  app/components/common/form/index.tsx
  app/components/common/form/terms.tsx
  app/components/common/index.ts
  app/components/common/link.tsx
  app/components/common/navigation.tsx
  app/components/my-tickets/ticket.tsx
  app/components/ticketing/card.tsx
  app/components/ui/checkbox.tsx
  app/global-error.tsx
  app/hooks/use-bottom-sheet.ts
  public/icons/feasta-logo.png
  public/icons/swifty-logo.svg
  public/sw.js
  public/sw.js.map
Labels: documentation

#71 재학생 재인증 대표 화면 추가
  app/[locale]/(back-nav)/(padded)/need-reverification/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/api/get-is-verified.ts
  app/components/home/index.ts
  app/components/home/need-reverification-tile.tsx
  public/icons/shield.png
Labels: enhancement

#72 학생인증 갱신되지 않은 상태 오류 핸들링
  app/[locale]/(back-nav)/(padded)/my-tickets/action.ts
  app/[locale]/(back-nav)/(padded)/my-tickets/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/action.ts
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/page.tsx
  app/lib/utils/validation/error/index.ts
Labels: bug

#74 v0.2.0
  .github/banner.webp
  README.md
  app/[locale]/(back-nav)/(padded)/my-tickets/action.ts
  app/[locale]/(back-nav)/(padded)/my-tickets/page.tsx
  app/[locale]/(back-nav)/(padded)/need-reverification/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/action.ts
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/api/get-is-verified.ts
  app/components/home/index.ts
  app/components/home/need-reverification-tile.tsx
  app/lib/utils/validation/error/index.ts
  package.json
  public/icons/shield.png
Labels: deploy

#77 Feat: 스토리북 서버사이드 렌더링 반영
  .storybook/main.ts
  README.md
  package.json
  stories/common/side-nav.stories.tsx
  stories/components/home/lineup-tiles.stories.tsx
  stories/components/home/need-reverification-tile.stories.tsx
  stories/components/home/notice-tile.stories.tsx
  stories/components/home/ticket-tile.stories.tsx
  stories/components/stamp/done-overlay.stories.tsx
  stories/components/ticketing/Form.stories.tsx
  stories/components/ticketing/card.stories.tsx
  yarn.lock
Labels: documentation, deploy

#82 hotfix: 닫은 화면
  app/[locale]/under-construction/layout.tsx
  app/[locale]/under-construction/loading.tsx
  app/[locale]/under-construction/page.tsx
  app/components/common/locale-switcher/locale-switcher-select.tsx
  app/components/under-construction/index.ts
  app/components/under-construction/remain-timer.tsx
  app/layout.tsx
  messages/en.json
  messages/ko.json
  middleware.ts
Labels: deploy

#87 어드민 비밀번호
  app/[locale]/(back-nav)/admin/page.tsx
  app/components/admin/action.ts
  app/components/my-tickets/ticket-tool.tsx
  middleware.ts
Labels: enhancement

#88 미션 정보 추가
  app/[locale]/(back-nav)/(padded)/stamp/[missionId]/page.tsx
  app/[locale]/(dark-scheme)/stamp/mission-info.ts
  app/[locale]/(dark-scheme)/stamp/page.tsx
  public/images/stamp/thumbnails/01_타투스티커.png
  public/images/stamp/thumbnails/02_슬로건.png
  public/images/stamp/thumbnails/03_드레스코드.png
  public/images/stamp/thumbnails/04_포토부스.png
  public/images/stamp/thumbnails/05_포토존.png
  public/images/stamp/thumbnails/06_핫타임_1.png
  public/images/stamp/thumbnails/07_핫타임_2.png
Labels: enhancement

#91 스탬프 투어 추가
  app/[locale]/(back-nav)/(padded)/stamp/[missionId]/page.tsx
  app/[locale]/(back-nav)/admin/page.tsx
  app/[locale]/(back-nav)/lineup/actions.ts
  app/[locale]/(dark-scheme)/stamp/mission-info.ts
  app/[locale]/(dark-scheme)/stamp/page.tsx
  app/api/get-is-user-info.ts
  app/api/get-is-verified.ts
  app/components/admin/action.ts
  app/components/home/lineup-tile.tsx
  app/components/home/need-reverification-tile.tsx
  app/components/my-tickets/ticket-tool.tsx
  middleware.ts
  public/images/stamp/thumbnails/드레스코드.png
  public/images/stamp/thumbnails/슬로건.png
  public/images/stamp/thumbnails/타투스티커.png
  public/images/stamp/thumbnails/포토부스.png
  public/images/stamp/thumbnails/포토존.png
  public/images/stamp/thumbnails/핫타임_1.png
  public/images/stamp/thumbnails/핫타임_2.png
Labels: deploy

#75 test: If 컴포넌트 test 코드 작성
  __tests__/unit/components/common/if.test.tsx
  tsconfig.json
Labels: test

#80 test: Form 컴포넌트 test 코드 작성
  __tests__/unit/components/common/form.test.tsx
  app/components/common/form/input.tsx
  app/components/ticketing/form.tsx
Labels: test

#94 59 라인업 페이지 수정
  app/[locale]/(back-nav)/(padded)/lineup/actions.ts
  app/[locale]/(back-nav)/(padded)/lineup/page.tsx
  app/[locale]/(back-nav)/lineup/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/home/lineup-tile.tsx
  app/components/lineup/date-selector/date-block.tsx
  app/components/lineup/date-selector/index.tsx
  app/components/lineup/index.ts
  app/lib/constants.ts
  app/lib/utils/parser/parse-festival-date.ts
  public/sw.js
  public/sw.js.map
  stories/components/common/ad-banner.stories.tsx
  stories/components/common/bottom-sheet.stories.tsx
  stories/components/common/button.stories.tsx
  stories/components/common/carousel.stories.tsx
  stories/components/common/floating-ticket.stories.tsx
  stories/components/common/footer.stories.tsx
  stories/components/common/form.stories.tsx
  stories/components/common/locale-switcher.stories.tsx
  stories/components/common/overlay.stories.tsx
  stories/components/common/side-nav.stories.tsx
  stories/components/lineup/date-block.stories.tsx
  stories/components/my-tickets/qr-code.stories.tsx
Labels: enhancement

#96 행사 내용 추가
  app/[locale]/(back-nav)/(padded)/events/page.tsx
  app/components/common/ad-banner/block.tsx
  app/components/common/ad-banner/carousel.tsx
  app/components/common/ad-banner/index.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/home/lineup-tile.tsx
  public/images/events/hottime_1.jpeg
  public/images/events/hottime_2.jpeg
  public/images/events/hottime_3.jpeg
  public/images/events/hottime_4.jpeg
  public/images/events/hottime_5.jpeg
  public/images/events/hottime_6.jpeg
  stories/components/common/carousel.stories.tsx
Labels: deploy

#97 chore: 버그 수정
  app/[locale]/(back-nav)/(padded)/signup/page.tsx
  app/[locale]/(back-nav)/login/page.tsx
  app/global-error.tsx
  app/not-found.tsx
  app/page.tsx
  middleware.ts
Labels: enhancement

#98 아이패드 오류 해결
  app/[locale]/(back-nav)/(padded)/need-reverification/page.tsx
  app/[locale]/(back-nav)/(padded)/signup/complete/page.tsx
  app/[locale]/(back-nav)/(padded)/ticketing/[eventId]/result/page.tsx
  app/[locale]/(back-nav)/admin/action.ts
  app/[locale]/(back-nav)/admin/page.tsx
  app/components/admin/result-tile/student-info.tsx
  app/components/common/ad-banner/index.tsx
  app/components/common/animated/animated-wrapper.tsx
  app/components/common/confetti.tsx
  app/components/my-tickets/ticket.tsx
  app/components/stamp/done-overlay.tsx
  middleware.ts
Labels: bug, enhancement

#111 feat: 모바일 뷰 유지하도록 수정
  app/[locale]/(back-nav)/(padded)/events/page.tsx
  app/[locale]/(back-nav)/admin/layout.tsx
  app/[locale]/(back-nav)/admin/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/[locale]/layout.tsx
  app/components/common/ad-banner/index.tsx
  app/components/common/bottom-sheet/index.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/footer.tsx
  app/components/common/navigation.tsx
  app/components/home/lineup-tile.tsx
  app/components/home/menu-tiles/index.tsx
  app/components/home/menu-tiles/tile.tsx
  app/components/home/tile-header.tsx
  app/layout.tsx
Labels: enhancement

#112 Dev
  app/[locale]/(back-nav)/(padded)/events/page.tsx
  app/[locale]/(back-nav)/admin/layout.tsx
  app/[locale]/(back-nav)/admin/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/[locale]/layout.tsx
  app/components/common/ad-banner/index.tsx
  app/components/common/bottom-sheet/index.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/common/footer.tsx
  app/components/common/navigation.tsx
  app/components/home/lineup-tile.tsx
  app/components/home/menu-tiles/index.tsx
  app/components/home/menu-tiles/tile.tsx
  app/components/home/tile-header.tsx
  app/layout.tsx
Labels: deploy

#114 hotfix: 화면 수정
  app/[locale]/layout.tsx
  app/layout.tsx
Labels: bug

#115 화면 핫픽스
  app/[locale]/layout.tsx
  app/layout.tsx
Labels: deploy

#117 오타 수정 deploy
  app/[locale]/(back-nav)/(padded)/notice/page.tsx
  app/[locale]/(back-nav)/layout.tsx
  app/[locale]/layout.tsx
  app/components/lineup/date-selector/date-block.tsx
  app/layout.tsx
Labels: deploy

#119 fix: 플레이스홀더 만들지 않도록 수정
  app/[locale]/(back-nav)/(padded)/lineup/actions.ts
  app/[locale]/(back-nav)/(padded)/lineup/page.tsx
  app/[locale]/(dark-scheme)/stamp/page.tsx
  app/components/common/back-button.tsx
  app/components/common/carousel/tile.tsx
Labels: enhancement

#120 성능 향상
  app/[locale]/(back-nav)/(padded)/lineup/actions.ts
  app/[locale]/(back-nav)/(padded)/lineup/page.tsx
  app/[locale]/(dark-scheme)/stamp/page.tsx
  app/components/common/back-button.tsx
  app/components/common/carousel/tile.tsx
Labels: deploy

#123 feat: 날짜 정적으로 수정
  app/components/lineup/date-selector/index.tsx
Labels: deploy

#124 feat: get으로 메서드 변경
  app/[locale]/(dark-scheme)/stamp/action.ts
Labels: deploy

#125 blurData 추가
  app/components/common/carousel/tile.tsx
Labels: deploy

#126 feat: dateselector 로직 수정
  app/[locale]/(back-nav)/(padded)/lineup/actions.ts
  app/[locale]/(back-nav)/(padded)/lineup/page.tsx
  app/components/common/carousel/index.tsx
  app/components/common/carousel/tile.tsx
  app/components/home/lineup-tile.tsx
  app/components/lineup/date-selector/date-block.tsx
  app/components/lineup/date-selector/index.tsx
  app/lib/constants.ts
  app/lib/types/festival.ts
  app/lib/types/index.ts
  app/lib/utils/parser/parse-festival-date.ts
  package.json
  stories/components/lineup/date-block.stories.tsx
  yarn.lock
Labels: deploy

#127 비밀번호 등록창에서 오류메시지 로깅
  app/[locale]/(back-nav)/(padded)/password/page.tsx
  app/components/lineup/date-selector/index.tsx
  public/images/stamp/tour_01.webp
  public/images/stamp/tour_03.webp
Labels: bug

#130 v1.0.1
  app/components/common/navigation.tsx
  package.json
Labels: deploy

#131 docs: 키워드 추가
  app/layout.tsx
  package.json
Labels: documentation

#137 v1.0.2
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  app/[locale]/(root-nav)/page.tsx
  app/components/home/menu-tiles/index.tsx
  app/components/ticketing/card.tsx
  app/layout.tsx
  messages/en.json
  messages/ko.json
  package.json
Labels: deploy

#139 chore: next 버전 업
  package.json
  yarn.lock
Labels: deploy

#140 종료된 티켓팅 숨기는 기능
  app/[locale]/(back-nav)/(padded)/ticketing/action.ts
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  app/components/ticketing/card.tsx
  app/components/ticketing/index.ts
  app/components/ticketing/show-all.tsx
  messages/en.json
  messages/ko.json
Labels: enhancement

#142 오픈전 보이도록 수정
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  package.json
Labels: enhancement

#143 v1.1.1
  app/[locale]/(back-nav)/(padded)/ticketing/page.tsx
  package.json
Labels: deploy
